version: '3.8'

services:
  streamlit:
    build:
      context: ./FrontEnd
      dockerfile: ./Streamlit/Dockerfile
    ports:
      - '80:80'
    restart: "no"
    depends_on:
      - fastapi

  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: moniaq
      MYSQL_USER: moniaq
      MYSQL_PASSWORD: admin
    ports:
      - "3307:3306"
    volumes:
      - ./data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: admin
    ports:
      - "8001:80"
    depends_on:
      - mariadb

  fastapi:
    build:
      context: ./BackEnd
      dockerfile: ./FastAPI/Dockerfile
    environment:
      PORT: 8000
      DATABASE_URL: mysql://moniaq:admin@mariadb:3306/moniaq
    ports:
      - '8002:80'
    restart: "no"
    depends_on:
      - mariadb

  vendor:
    build:
      context: ./BackEnd
      dockerfile: ./vendor/Dockerfile
    restart: "no"
    environment:
      DATABASE_URL: mysql://moniaq:admin@mariadb:3306/moniaq
    depends_on:
      - mariadb
      - fastapi