import streamlit as st
import plotly.express as px
import pandas as pd
import numpy as np
st.set_page_config(page_title="MONAQ - Senzor",page_icon="📈")
SoTD = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
# SoTD = Screams Of The Damned
st.header("Senzor: 0",divider="rainbow")

chart_data = pd.DataFrame(
{
    "Time": np.random.randn(20),
    "Temperature": np.random.randn(20),
    "col3": np.random.randint(1,20),
    "Humidity": np.random.randn(20),
    "CO₂": np.random.randn(20),
}
)
with st.container(border=True):
    st.header("Temperature", divider="orange")
    st.line_chart(chart_data, x="Time", y="Temperature", color="#FFA500")    #teplota
    st.header("Humidity", divider="blue")
    st.line_chart(chart_data, x="Time", y="Humidity", color="#006FAF")    #vlhkost
    st.header("CO₂", divider="grey")
    st.line_chart(chart_data, x="Time", y="CO₂", color="#90999F")    #CO2
K, D, M = st.columns(3)
with K:
    with st.container(border=True):
        st.write("DD/MM/YYYY - HH:MM:SS")
with D:
    with st.container(border=True):
        st.write("Status: Online")
with M:
    with st.container(border=True):
        st.write("Sensor Number: 420")

st.write("e")